name: static build
on: [push]

env:
  VCPKG_LIBRARY_LINKAGE: static

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get install libwayland-dev libxkbcommon-dev libegl1-mesa-dev libx11-dev libxft-dev libxext-dev ninja-build

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. --preset default
        ninja -v
        strip ezquake
        zip -9 ezquake.zip ezquake
        mv ezquake.zip ..

    - uses: actions/upload-artifact@v3
      with:
        name: ezquake-static
        path: ezquake.zip
